// ====================================================================
// G-TECH ISP OPERATING SYSTEM - IN-MEMORY SEED & STATE ENGINE
// Realistic production-grade sample dataset for Kenyan ISP operation
// ====================================================================

import type {
  Organization,
  User,
  Site,
  Router,
  ServicePlan,
  Customer,
  PppoeAccount,
  Subscription,
  VoucherBatch,
  HotspotVoucher,
  Payment,
  Invoice,
  WorkOrder,
  NetworkAlert,
  NOCStats,
} from "../../types/index.ts";

export const SEED_ORGANIZATION: Organization = {
  id: "org-nexanet-01",
  name: "QC NetCore",
  slug: "nexanet-technologies",
  businessNumber: "BN-2024-9812",
  email: "support@nexanet.co.ke",
  phone: "+254712345678",
  currency: "KES",
  timezone: "Africa/Nairobi",
  billingCycleType: "ANNIVERSARY",
  gracePeriodDays: 2,
  isActive: true,
  createdAt: "2025-01-01T08:00:00Z",
};

export const SEED_USERS: User[] = [
  {
    id: "user-owner-01",
    organizationId: SEED_ORGANIZATION.id,
    email: "admin@gtechisp.co.ke",
    fullName: "Baraka Gackstone",
    phoneNumber: "+254712345678",
    role: "isp_owner",
    isActive: true,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "user-tech-01",
    organizationId: SEED_ORGANIZATION.id,
    email: "brian.tech@gtechisp.co.ke",
    fullName: "Brian Kiprop",
    phoneNumber: "+254722334455",
    role: "technician",
    isActive: true,
    createdAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "user-cust-01",
    organizationId: SEED_ORGANIZATION.id,
    email: "john.kamau@gmail.com",
    fullName: "John Kamau Mwangi",
    phoneNumber: "+254799112233",
    role: "customer",
    isActive: true,
    createdAt: "2025-02-01T12:00:00Z",
  },
];

export const SEED_SITES: Site[] = [
  {
    id: "site-01",
    organizationId: SEED_ORGANIZATION.id,
    name: "Nairobi CBD - Tower POP",
    locationDescription: "Kenyatta Avenue, City House 12th Floor",
    latitude: -1.286389,
    longitude: 36.817223,
    powerBackupType: "GENERATOR",
    routerCount: 2,
    customerCount: 38,
    createdAt: "2025-01-02T08:00:00Z",
  },
  {
    id: "site-02",
    organizationId: SEED_ORGANIZATION.id,
    name: "Westlands - Ring Road Core",
    locationDescription: "Sarit Centre Wireless Mast #4",
    latitude: -1.2618,
    longitude: 36.8044,
    powerBackupType: "SOLAR",
    routerCount: 1,
    customerCount: 24,
    createdAt: "2025-01-05T08:00:00Z",
  },
  {
    id: "site-03",
    organizationId: SEED_ORGANIZATION.id,
    name: "Kilimani - Argwings Kodhek Base",
    locationDescription: "Yaya Center Tower B",
    latitude: -1.2952,
    longitude: 36.7865,
    powerBackupType: "UPS",
    routerCount: 1,
    customerCount: 19,
    createdAt: "2025-01-12T08:00:00Z",
  },
];

export const SEED_ROUTERS: Router[] = [
  {
    id: "rtr-01",
    organizationId: SEED_ORGANIZATION.id,
    siteId: "site-01",
    siteName: "Nairobi CBD - Tower POP",
    name: "MikroTik-Core-CCR2004",
    managementIp: "10.200.1.2",
    apiPort: 8728,
    apiSslPort: 8729,
    username: "gtech_admin",
    routerosVersion: "v7.16.1",
    boardModel: "CCR2004-16G-2S+",
    cpuLoad: 14,
    freeMemoryMb: 3420,
    uptime: "48d 14h 22m",
    connectionType: "WIREGUARD",
    wireguardPublicKey: "tY829hskLmqP81nZ+J298slk1jkw829js91jkmsi1==",
    wireguardTunnelIp: "10.200.1.2",
    status: "ONLINE",
    lastSeenAt: new Date().toISOString(),
    activeSessions: 62,
    createdAt: "2025-01-02T08:00:00Z",
  },
  {
    id: "rtr-02",
    organizationId: SEED_ORGANIZATION.id,
    siteId: "site-02",
    siteName: "Westlands - Ring Road Core",
    name: "MikroTik-Westlands-RB5009",
    managementIp: "10.200.1.3",
    apiPort: 8728,
    apiSslPort: 8729,
    username: "gtech_admin",
    routerosVersion: "v7.15.3",
    boardModel: "RB5009UG+S+IN",
    cpuLoad: 28,
    freeMemoryMb: 768,
    uptime: "19d 08h 11m",
    connectionType: "WIREGUARD",
    wireguardPublicKey: "kL0192jksmLqp189jsms091jklms82901ksm018==",
    wireguardTunnelIp: "10.200.1.3",
    status: "ONLINE",
    lastSeenAt: new Date().toISOString(),
    activeSessions: 34,
    createdAt: "2025-01-05T08:00:00Z",
  },
  {
    id: "rtr-03",
    organizationId: SEED_ORGANIZATION.id,
    siteId: "site-03",
    siteName: "Kilimani - Argwings Kodhek Base",
    name: "MikroTik-Kilimani-hEX",
    managementIp: "10.200.1.4",
    apiPort: 8728,
    apiSslPort: 8729,
    username: "gtech_admin",
    routerosVersion: "v7.14.2",
    boardModel: "RB750Gr3",
    cpuLoad: 42,
    freeMemoryMb: 112,
    uptime: "5d 02h 45m",
    connectionType: "WIREGUARD",
    wireguardPublicKey: "mQ982jsklmp9812jks9018jksm82901jksm0182==",
    wireguardTunnelIp: "10.200.1.4",
    status: "ONLINE",
    lastSeenAt: new Date().toISOString(),
    activeSessions: 18,
    createdAt: "2025-01-12T08:00:00Z",
  },
];

export const SEED_PLANS: ServicePlan[] = [
  // PPPoE Residential & Business Plans
  {
    id: "plan-pppoe-5m",
    organizationId: SEED_ORGANIZATION.id,
    name: "Bronze Fiber - 5 Mbps",
    serviceType: "PPPOE",
    downloadSpeedKbps: 5120,
    uploadSpeedKbps: 2560,
    priority: 8,
    validityDurationSeconds: 2592000, // 30 days
    dataLimitMb: 0,
    price: 1500,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "2560k/5120k",
    isActive: true,
    subscriberCount: 22,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "plan-pppoe-10m",
    organizationId: SEED_ORGANIZATION.id,
    name: "Silver Fiber - 10 Mbps",
    serviceType: "PPPOE",
    downloadSpeedKbps: 10240,
    uploadSpeedKbps: 5120,
    burstDownloadKbps: 15360,
    burstUploadKbps: 7680,
    burstThresholdKbps: 8192,
    burstTimeSeconds: 15,
    priority: 7,
    validityDurationSeconds: 2592000,
    dataLimitMb: 0,
    price: 2500,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "5120k/10240k 7680k/15360k 4096k/8192k 15/15 7 2048k/4096k",
    isActive: true,
    subscriberCount: 45,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "plan-pppoe-20m",
    organizationId: SEED_ORGANIZATION.id,
    name: "Gold Fiber - 20 Mbps",
    serviceType: "PPPOE",
    downloadSpeedKbps: 20480,
    uploadSpeedKbps: 10240,
    burstDownloadKbps: 30720,
    burstUploadKbps: 15360,
    priority: 5,
    validityDurationSeconds: 2592000,
    dataLimitMb: 0,
    price: 4000,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "10M/20M",
    isActive: true,
    subscriberCount: 14,
    createdAt: "2025-01-01T08:00:00Z",
  },
  // Hotspot Prepaid Packages
  {
    id: "plan-hs-1h",
    organizationId: SEED_ORGANIZATION.id,
    name: "Hotspot 1 Hour Express",
    serviceType: "HOTSPOT",
    downloadSpeedKbps: 3072,
    uploadSpeedKbps: 1536,
    priority: 8,
    validityDurationSeconds: 3600, // 1 hour
    dataLimitMb: 0,
    price: 10,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "1536k/3072k",
    isActive: true,
    subscriberCount: 350,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "plan-hs-3h",
    organizationId: SEED_ORGANIZATION.id,
    name: "Hotspot 3 Hours Special",
    serviceType: "HOTSPOT",
    downloadSpeedKbps: 4096,
    uploadSpeedKbps: 2048,
    priority: 8,
    validityDurationSeconds: 10800, // 3 hours
    dataLimitMb: 0,
    price: 20,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "2048k/4096k",
    isActive: true,
    subscriberCount: 420,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "plan-hs-24h",
    organizationId: SEED_ORGANIZATION.id,
    name: "Hotspot Daily Basic",
    serviceType: "HOTSPOT",
    downloadSpeedKbps: 5120,
    uploadSpeedKbps: 2560,
    priority: 7,
    validityDurationSeconds: 86400, // 24 hours (1 Day)
    dataLimitMb: 0,
    price: 50,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "2560k/5120k",
    isActive: true,
    subscriberCount: 280,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "plan-hs-7d",
    organizationId: SEED_ORGANIZATION.id,
    name: "Hotspot Weekly Plus",
    serviceType: "HOTSPOT",
    downloadSpeedKbps: 10240,
    uploadSpeedKbps: 5120,
    priority: 6,
    validityDurationSeconds: 604800, // 7 days
    dataLimitMb: 0,
    price: 250,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "5120k/10240k",
    isActive: true,
    subscriberCount: 95,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "plan-hs-30d",
    organizationId: SEED_ORGANIZATION.id,
    name: "Hotspot Monthly Pro",
    serviceType: "HOTSPOT",
    downloadSpeedKbps: 20480,
    uploadSpeedKbps: 10240,
    priority: 6,
    validityDurationSeconds: 2592000, // 30 days
    dataLimitMb: 0,
    price: 800,
    currency: "KES",
    simultaneousSessions: 1,
    mikrotikRateLimit: "10240k/20480k",
    isActive: true,
    subscriberCount: 65,
    createdAt: "2025-01-01T08:00:00Z",
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "cust-01",
    organizationId: SEED_ORGANIZATION.id,
    accountNumber: "GT-8921",
    fullName: "John Kamau Mwangi",
    phoneNumber: "0799112233",
    email: "john.kamau@gmail.com",
    nationalId: "31849201",
    physicalAddress: "Kilimani, Menelik Road, Apt 4B",
    siteId: "site-03",
    siteName: "Kilimani - Argwings Kodhek Base",
    status: "ACTIVE",
    balanceDue: 0,
    createdAt: "2025-01-10T12:00:00Z",
  },
  {
    id: "cust-02",
    organizationId: SEED_ORGANIZATION.id,
    accountNumber: "GT-8922",
    fullName: "Grace Njeri Otieno",
    phoneNumber: "0712987654",
    email: "grace.otieno@outlook.com",
    nationalId: "28491024",
    physicalAddress: "Westlands, Muthithi Road, Suite 2",
    siteId: "site-02",
    siteName: "Westlands - Ring Road Core",
    status: "ACTIVE",
    balanceDue: 0,
    createdAt: "2025-01-14T09:30:00Z",
  },
  {
    id: "cust-03",
    organizationId: SEED_ORGANIZATION.id,
    accountNumber: "GT-8923",
    fullName: "David Kipchumba Koech",
    phoneNumber: "0720445566",
    email: "david.koech@gmail.com",
    nationalId: "34910283",
    physicalAddress: "CBD, City House 5th Floor",
    siteId: "site-01",
    siteName: "Nairobi CBD - Tower POP",
    status: "SUSPENDED",
    balanceDue: 2500,
    createdAt: "2025-01-18T14:15:00Z",
  },
  {
    id: "cust-04",
    organizationId: SEED_ORGANIZATION.id,
    accountNumber: "GT-8924",
    fullName: "Faith Wangari Ndung'u",
    phoneNumber: "0741223344",
    email: "faith.wangari@yahoo.com",
    nationalId: "29841203",
    physicalAddress: "Kilimani, Wood Avenue, House 12",
    siteId: "site-03",
    siteName: "Kilimani - Argwings Kodhek Base",
    status: "ACTIVE",
    balanceDue: 0,
    createdAt: "2025-01-20T11:00:00Z",
  },
  {
    id: "cust-05",
    organizationId: SEED_ORGANIZATION.id,
    accountNumber: "GT-8925",
    fullName: "Ahmed Hassan Omar",
    phoneNumber: "0722889900",
    email: "ahmed.omar@gmail.com",
    nationalId: "33890124",
    physicalAddress: "Parklands, 3rd Parklands Ave",
    siteId: "site-02",
    siteName: "Westlands - Ring Road Core",
    status: "PENDING_INSTALLATION",
    balanceDue: 4000,
    createdAt: "2025-02-01T10:00:00Z",
  },
];

export const SEED_PPPOE: PppoeAccount[] = [
  {
    id: "pppoe-01",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-01",
    routerId: "rtr-03",
    username: "gt_john_kamau",
    passwordPlain: "Kamau#2025",
    servicePlanId: "plan-pppoe-10m",
    ipAssignmentType: "POOL",
    macAddress: "D4:6E:0E:12:34:56",
    isActive: true,
    isOnline: true,
    currentIp: "10.10.12.45",
    uptime: "4d 18h 32m",
    bytesIn: 48920194820,
    bytesOut: 189201948200,
  },
  {
    id: "pppoe-02",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-02",
    routerId: "rtr-02",
    username: "gt_grace_otieno",
    passwordPlain: "Grace#9821",
    servicePlanId: "plan-pppoe-20m",
    ipAssignmentType: "STATIC",
    staticIp: "10.10.10.14",
    macAddress: "BC:24:11:98:76:54",
    isActive: true,
    isOnline: true,
    currentIp: "10.10.10.14",
    uptime: "12d 02h 14m",
    bytesIn: 112920194820,
    bytesOut: 489201948200,
  },
  {
    id: "pppoe-03",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-03",
    routerId: "rtr-01",
    username: "gt_david_koech",
    passwordPlain: "Koech#Pass1",
    servicePlanId: "plan-pppoe-10m",
    ipAssignmentType: "POOL",
    isActive: false,
    isOnline: false,
    uptime: "0s",
    bytesIn: 0,
    bytesOut: 0,
  },
  {
    id: "pppoe-04",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-04",
    routerId: "rtr-03",
    username: "gt_faith_wangari",
    passwordPlain: "Faith#Pass4",
    servicePlanId: "plan-pppoe-5m",
    ipAssignmentType: "POOL",
    macAddress: "E0:D5:5E:44:33:22",
    isActive: true,
    isOnline: true,
    currentIp: "10.10.12.89",
    uptime: "1d 04h 10m",
    bytesIn: 12920194820,
    bytesOut: 52920194820,
  },
];

export const SEED_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub-01",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-01",
    planId: "plan-pppoe-10m",
    planName: "Silver Fiber - 10 Mbps",
    startTime: "2025-01-10T00:00:00Z",
    endTime: new Date(Date.now() + 18 * 86400000).toISOString(),
    status: "ACTIVE",
    autoRenew: true,
    lastRenewedAt: "2025-02-10T00:00:00Z",
    createdAt: "2025-01-10T00:00:00Z",
  },
  {
    id: "sub-02",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-02",
    planId: "plan-pppoe-20m",
    planName: "Gold Fiber - 20 Mbps",
    startTime: "2025-01-14T00:00:00Z",
    endTime: new Date(Date.now() + 24 * 86400000).toISOString(),
    status: "ACTIVE",
    autoRenew: true,
    lastRenewedAt: "2025-02-14T00:00:00Z",
    createdAt: "2025-01-14T00:00:00Z",
  },
  {
    id: "sub-03",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-03",
    planId: "plan-pppoe-10m",
    planName: "Silver Fiber - 10 Mbps",
    startTime: "2025-01-01T00:00:00Z",
    endTime: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: "SUSPENDED",
    autoRenew: false,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "sub-04",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-04",
    planId: "plan-pppoe-5m",
    planName: "Bronze Fiber - 5 Mbps",
    startTime: "2025-01-20T00:00:00Z",
    endTime: new Date(Date.now() + 28 * 86400000).toISOString(),
    status: "ACTIVE",
    autoRenew: true,
    lastRenewedAt: "2025-02-20T00:00:00Z",
    createdAt: "2025-01-20T00:00:00Z",
  },
];

export const SEED_PAYMENTS: Payment[] = [
  {
    id: "pay-01",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-01",
    customerName: "John Kamau Mwangi",
    accountNumber: "GT-8921",
    paymentMethod: "MPESA_EXPRESS",
    amount: 2500,
    currency: "KES",
    transactionReference: "RKF9283KDJ",
    msisdnPhone: "254799112233",
    senderName: "JOHN KAMAU",
    status: "COMPLETED",
    processedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: "pay-02",
    organizationId: SEED_ORGANIZATION.id,
    customerId: "cust-02",
    customerName: "Grace Njeri Otieno",
    accountNumber: "GT-8922",
    paymentMethod: "MPESA_C2B",
    amount: 4000,
    currency: "KES",
    transactionReference: "RKF8841LPS",
    msisdnPhone: "254712987654",
    senderName: "GRACE OTIENO",
    status: "COMPLETED",
    processedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: "pay-03",
    organizationId: SEED_ORGANIZATION.id,
    paymentMethod: "MPESA_EXPRESS",
    amount: 50,
    currency: "KES",
    transactionReference: "RKF7730MNQ",
    msisdnPhone: "254708112244",
    senderName: "PETER MAINA",
    status: "COMPLETED",
    processedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: "pay-04",
    organizationId: SEED_ORGANIZATION.id,
    paymentMethod: "MPESA_EXPRESS",
    amount: 20,
    currency: "KES",
    transactionReference: "RKF6612QAZ",
    msisdnPhone: "254722556677",
    senderName: "ALICE WANJIKU",
    status: "COMPLETED",
    processedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
];

export const SEED_VOUCHER_BATCHES: VoucherBatch[] = [
  {
    id: "batch-01",
    organizationId: SEED_ORGANIZATION.id,
    planId: "plan-hs-1h",
    planName: "Hotspot 1 Hour Express (KSh 10)",
    batchName: "Kenyatta Ave Station - 100x 1Hr",
    quantity: 100,
    prefix: "GT1H",
    generatedByName: "Baraka Gackstone",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "batch-02",
    organizationId: SEED_ORGANIZATION.id,
    planId: "plan-hs-24h",
    planName: "Hotspot 24 Hours Unlimited (KSh 50)",
    batchName: "Westlands Sarit Hub - 50x 24Hr",
    quantity: 50,
    prefix: "GT24",
    generatedByName: "Baraka Gackstone",
    createdAt: "2025-02-05T14:30:00Z",
  },
];

export const SEED_HOTSPOT_VOUCHERS: HotspotVoucher[] = [
  {
    id: "vch-01",
    organizationId: SEED_ORGANIZATION.id,
    batchId: "batch-01",
    planId: "plan-hs-1h",
    planName: "1 Hour Express",
    planPrice: 10,
    planDuration: "1 Hour",
    code: "GT1H-9842-KLP",
    status: "AVAILABLE",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "vch-02",
    organizationId: SEED_ORGANIZATION.id,
    batchId: "batch-01",
    planId: "plan-hs-1h",
    planName: "1 Hour Express",
    planPrice: 10,
    planDuration: "1 Hour",
    code: "GT1H-3918-BVC",
    status: "AVAILABLE",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "vch-03",
    organizationId: SEED_ORGANIZATION.id,
    batchId: "batch-01",
    planId: "plan-hs-1h",
    planName: "1 Hour Express",
    planPrice: 10,
    planDuration: "1 Hour",
    code: "GT1H-7741-MNQ",
    status: "USED",
    firstActivatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 60000).toISOString(),
    usedByPhone: "0711998877",
    usedMacAddress: "AA:BB:CC:11:22:33",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "vch-04",
    organizationId: SEED_ORGANIZATION.id,
    batchId: "batch-02",
    planId: "plan-hs-24h",
    planName: "24 Hours Unlimited",
    planPrice: 50,
    planDuration: "24 Hours",
    code: "GT24-6629-XYZ",
    status: "AVAILABLE",
    createdAt: "2025-02-05T14:30:00Z",
  },
  {
    id: "vch-05",
    organizationId: SEED_ORGANIZATION.id,
    batchId: "batch-02",
    planId: "plan-hs-24h",
    planName: "24 Hours Unlimited",
    planPrice: 50,
    planDuration: "24 Hours",
    code: "GT24-1184-QRS",
    status: "AVAILABLE",
    createdAt: "2025-02-05T14:30:00Z",
  },
];

export const SEED_WORK_ORDERS: WorkOrder[] = [
  {
    id: "wo-01",
    organizationId: SEED_ORGANIZATION.id,
    ticketNumber: "WO-2025-001",
    customerId: "cust-05",
    customerName: "Ahmed Hassan Omar",
    customerPhone: "0722889900",
    customerAddress: "Parklands, 3rd Parklands Ave",
    assignedTechnicianId: "user-tech-01",
    assignedTechnicianName: "Brian Kiprop",
    title: "New Fiber Drop & ONU Installation",
    description: "Run 80m drop fiber cable from FAT #3 to apartment 4, configure Huawei HG8310M ONU and TP-Link Archer C6 router.",
    orderType: "INSTALLATION",
    priority: "HIGH",
    status: "ASSIGNED",
    scheduledDate: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    createdAt: "2025-02-01T10:30:00Z",
  },
  {
    id: "wo-02",
    organizationId: SEED_ORGANIZATION.id,
    ticketNumber: "WO-2025-002",
    customerId: "cust-01",
    customerName: "John Kamau Mwangi",
    customerPhone: "0799112233",
    customerAddress: "Kilimani, Menelik Road, Apt 4B",
    assignedTechnicianId: "user-tech-01",
    assignedTechnicianName: "Brian Kiprop",
    title: "Fiber Splicing & Signal Loss Diagnosis",
    description: "Customer reports high packet loss. Inspect fiber attenuation (target optical power: -19 dBm to -24 dBm).",
    orderType: "REPAIR",
    priority: "CRITICAL",
    status: "IN_PROGRESS",
    scheduledDate: new Date().toISOString().split("T")[0],
    createdAt: "2025-02-02T08:15:00Z",
  },
];

export const SEED_ALERTS: NetworkAlert[] = [
  {
    id: "alt-01",
    organizationId: SEED_ORGANIZATION.id,
    routerId: "rtr-01",
    routerName: "MikroTik-Core-CCR2004",
    severity: "INFO",
    title: "BGP Upstream Flap Resolved",
    message: "Liquid Telecom BGP Session 185.20.10.1 converged after 12s flap.",
    isResolved: true,
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: "alt-02",
    organizationId: SEED_ORGANIZATION.id,
    routerId: "rtr-03",
    routerName: "MikroTik-Kilimani-hEX",
    severity: "WARNING",
    title: "CPU Threshold Warning",
    message: "Router CPU reached 42% under heavy evening PPPoE load.",
    isResolved: false,
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
];

export function getSeedNOCStats(): NOCStats {
  return {
    totalSubscribers: 81,
    activeSubscribers: 76,
    onlinePppoe: 58,
    onlineHotspot: 56,
    expiringIn24h: 3,
    suspendedCount: 5,
    totalRouters: 3,
    onlineRouters: 3,
    currentBandwidthMbps: {
      download: 284.6,
      upload: 118.2,
    },
    revenueToday: 18450,
    revenueThisMonth: 342500,
    recentAlerts: SEED_ALERTS,
  };
}
